version: '3'

services:
   openvpn:
     image: kylemanna/openvpn
     container_name: openvpn
     restart: unless-stopped
     cap_add:
       - NET_ADMIN
     ports:
       - "1194:1194/udp"
       - "1194:1194/tcp"
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
       - ./openvpn-data:/etc/openvpn
     networks:
       vpn-net:
         ipv4_address: 172.110.1.3
     labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

   pihole:
     image: pihole/pihole
     container_name: pihole
     restart: unless-stopped
     cap_add:
       - NET_ADMIN
     dns:
       - 127.0.0.1
       - 1.1.1.1
     depends_on:
       - openvpn
     volumes:
       - ./etc-pihole:/etc/pihole
       - ./etc-dnsmasq.d:/etc/dnsmasq.d
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
     environment:
       TZ: Europe/Paris
     networks:
       vpn-net:
         ipv4_address: 172.110.1.4
       proxy:
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${TRAEFIK_PIHOLE}`)"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=mydnschallenge"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

# docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
networks:
  proxy:
    external: true
  vpn-net:
    driver: bridge
    subnet: 172.110.1.0/24
    gateway: 172.110.1.1
    external: true