entryPoints:
  http:
    address: ":80"
    # Uncomment the following middleware if you are using crowdsec
    #http:
    #  middlewares:
    #    - middleware-crowdsec-bouncer@file

  https:
    address: ":443"
    # Uncomment the following middleware if you are using crowdsec
    #http:
    #  middlewares:
    #    - middleware-crowdsec-bouncer@file

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false

  file:
    directory: /rules
    watch: true

certificatesResolvers:
  mydnschallenge:
    acme:
      email: mail@example.com
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10

log:
  level: INFO