entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - secHeader@file
        # Uncomment the following middleware if you are using crowdsec
        #- middleware-crowdsec-bouncer@file

  https:
    address: ":443"
    http:
      middlewares:
        - secHeader@file
        # Uncomment the following middleware if you are using crowdsec
        #- middleware-crowdsec-bouncer@file

providers:
  docker:
    network: proxy
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false

  file:
    directory: /rules
    watch: true

certificatesResolvers:
  mydnschallenge:
    acme:
      email: mail@example.com
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10

log:
  level: INFO